services:
  - type: worker
    name: vwap-trading-bot
    runtime: docker
    dockerfilePath: ./Dockerfile.vwap
    plan: starter
    envVars:
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: TWILIO_TO
        sync: false
      - key: TRADE_LOG_PATH
        value: /data/trades.csv
    disk:
      name: trade-logs-vwap
      mountPath: /data
      sizeGB: 1

  - type: worker
    name: orb-trading-bot
    runtime: docker
    dockerfilePath: ./Dockerfile.orb
    plan: starter
    envVars:
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: TWILIO_TO
        sync: false
      - key: TRADE_LOG_PATH
        value: /data/trades.csv
    disk:
      name: trade-logs-orb
      mountPath: /data
      sizeGB: 1
